apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vprodb
  labels:
    app:  vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app:  vprodb
    spec:
      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vpro-db-data
      containers:
      - name:  vprodb
        image:  vprocontainers/vprofiledb
        resources:
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
        ports:
        - containerPort:  3306
          name:  vprodb-port
        volumeMounts:
        - name: vpro-db-data
          mountPath: /var/lib/mysql
      volumes:
        - name: vpro-db-data
          persistentVolumeClaim:
            claimName: db-pv-claim